export const CART = {
  ADD: "ADD",
  REMOVE: "REMOVE",
};

export const PRODUCTS = {
  FETCH_SUCCESS: "PRODUCTS_FETCH_SUCCESS",
  FETCH_ERROR: "PRODUCTS_FETCH_ERROR",
};

export const PRODUCT = {
  FETCH_SUCCESS: "PRODUCT_FETCH_SUCCESS",
  FETCH_ERROR: "PRODUCT_FETCH_ERROR",
};

export const LOGIN = {
  FETCH_SUCCESS: "LOGIN_SUCCESS",
  FETCH_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOG_OUT",
};
